version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www/web

  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/web
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  redis:
    image: redis:5
